name: deploy
run-name: "[RUN]: ${{github.actor}} deploy ${{github.repository}} to the server"
on:
  push:
    branches:
      - env/prod
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          command_timeout: 200m
          host: elsombrero.pro
          username: elsombrero
          port: 22
          password: ${{secrets.SSH_PASSWORD}}
          script: |
            cd deploy
            mkdir sudoku
            cd sudoku
            git clone https://github.com/ElSombrero2/Sudoku .
            git checkout env/prod
            git branch
            docker-compose up -d --build --force-recreate
            cd ..
            rm -rf sudoku